### ISSUE TITLE
Only checks for `developer_name` which is now deprecated and replaced by `developer` (only since AppStream 1.0)

### ISSUE THREAD

**Issue by travier** [flathub-infra/flatpak-builder-lint#274]
Since AppStream 1.0 release (https://github.com/ximion/appstream/blob/edb25f166d43df9a489c26ef78548bb37b730981/NEWS#L76), the [`developer_name`](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer_name) tag is now deprecated and replaced by [`developer`](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer).

The linter currently only checks for the `developer_name` tag: https://github.com/flathub-infra/flatpak-builder-lint/blob/7105a9643543123ffa487aada296ac462b2dbd66/flatpak_builder_lint/appstream.py#L39

**Comment by travier** [comment]
Yes, we likely also want to support pre-appstream 1.0 systems for a while so there is no rush. I raised this issue so that we have a trace.

**Comment by bbhtt** [comment]
Solved by https://github.com/flathub-infra/flatpak-builder-lint/commit/7bcac8e2eba9f2d2e06bd9d752972036c3f0e6c9

I'm switching the recommendation to `developer` with the `name` child tag in docs. https://github.com/flathub-infra/documentation https://github.com/flathub-infra/documentation/pull/228

**Comment by travier** [comment]
I'm not sure we can do that yet. Have you verified that older appstream accept the new developer tag?

**Comment by bbhtt** [comment]
Looks like "older" appstreamcli 0.16.1 (the version shipped in Fedora 39 right now), emits a harmless warning "unknown-tag-developer" on `appstreamcli validate` but the composed catalogue data removes the new developer tag (tested it on the Slack package). So that's going to get caught by the linter unless you have `developer_name` too in the metainfo file. Maybe @ximion can elaborate more on this.

I guess if your upstream CI still has to use older appstream (be it as-glib or appstreamcli), continue using `developer_name` and everything should work on Flathub/linter.

So from the linter's perspective the issue in the title is solved.

**Comment by ximion** [comment]
Is there a chance older CI could update to AppStream 0.16.4, potentially? That would also resolve it without introducing any breaking changes.

**Comment by bbhtt** [comment]
Let's close this. I see it is being discussed and resolved on the KDE side https://invent.kde.org/packaging/flatpak-kde-applications/-/issues/5

The original issue in the title is solved anyways.
